events {
    worker_connections 1024;
}

http {
    upstream account { server account:8000; }
    upstream session { server session:8000; }
    upstream matchmaking { server matchmaking:8000; }
    upstream stats { server stats:8000; }
    upstream catalog { server catalog:8000; }

    server {
        listen 80;

        location /auth/    { proxy_pass http://account; }
        location /profile/   { proxy_pass http://account; }
        location /friends/   { proxy_pass http://account; }

        location /session/        { proxy_pass http://session; }
        location /internal/       { proxy_pass http://session; }

        location /queue/     { proxy_pass http://matchmaking; }

        location /leaderboard/  { proxy_pass http://stats; }
        location /stats/        { proxy_pass http://stats; }
        location /matches/      { proxy_pass http://stats; }

        location /teams/      { proxy_pass http://catalog; }
        location /stadiums/   { proxy_pass http://catalog; }
    }
}
